### ISSUE TITLE
wg memory error: cannot attach to shared memory (No permission). with gtest

### ISSUE THREAD

**Issue by aleksandergabriel** [priitj/whitedb#49]
I am using WhiteDB with logging enabled. Under normal conditions everything is working as expected. But when I try to test my code with gtest-s I get `wg memory error: cannot attach to shared memory (No permission).` error when calling `wg_attach_database(&DB_NAME[0], size)` or  `wg_attach_logged_database(&DB_NAME[0], size)`. 
The same test was working fine when I was using WhiteDB with logging disabled. 
Are there any known issues with gtest-s? Or perhaps what exactly does this error points to?

Best regards
Aleksandergabriel

**Comment by priitj** [comment]
Hi,

this would normally happen only when the user who created the database is different than the one attaching.

Since the only way of reproducing it, as far as we know, is inside your tests, I am not sure how to approach this. Can you try to make a minimal test program that I could run and debug?

One quick check you can do is to make sure that the parameters to the wg_attach_* functions are exactly the same in all cases.

**Comment by aleksandergabriel** [comment]
After rechecking parameters I noticed that there was an extra space in the name of db ("test db") instead of integer or "test_db". After changing to proper format it works fine.
Thank you for your help. I believe this issue can be closed.
